#!/usr/bin/env bash
# audit a domain name with a subdomain or not
da() {
    if [ -z "$2" ]; then
        dig wwww."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
        dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
        dig web-01."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
        dig web-02."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    elif [ "$2" == "www" ]; then
        dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
    elif [ "$2" == "lb-01" ]; then
        dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    elif [ "$2" == "web-01" ]; then
        dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    elif [ "$2" == "web-02" ]; then
        dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    fi
}

if [ "$#" -eq 1 ]; then
    da "$1"
fi
if [ "$#" -eq 2 ]; then
    da "$1" "$2"
fi
