#!/usr/bin/env bash
# Installing HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.origina.cfg

sudo sed -i "$ a\listen 3402-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\tserver 3402-web-01 34.75.115.12:80 check\n\tserver 3402-web-02 54.92.203.11:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
