#!/usr/bin/env bash
# Installing HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.origina.cfg

sudo sed -i "$ a\\nfronted http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 3402-web-01 34.75.115.12:80 check\n\tserver 3402-web-02 54.92.203.11:80 check" /etc/haproxy/haproxy.cfg
  
sudo service haproxy restart
