#!/usr/bin/env bash
# Manage a deamon with init.d file
if [ "${1}" = start ]; then
        ./manage_my_process &
        file_pid=my_process.pid
        pgrep -f manage_my_process > $file_pid
        sudo mv $file_pid /var/run/my_process.pid
        echo "manage_my_process started"
elif [ "${1}" = stop ]; then
        pkill -F /var/run/my_process.pid
        sudo rm /var/run/my_process.pid
        echo "manage_my_process stopped"
elif [ "${1}" = restart ]; then
        pkill -F /var/run/my_process.pid
        sudo rm /var/run/my_process.pid
        ./manage_my_process &
        file_pid=my_process.pid
        pgrep -f manage_my_process > $file_pid
        sudo mv $file_pid /var/run/my_process.pid
        echo "manage_my_process restarted"
elif [ -z "${1}" ]; then
        echo "Usage: manage_my_process {start|stop|restart}"
elif [ -n "${2}" ]; then
        echo "Usage: manage_my_process {start|stop|restart}"
else
        echo "Usage: manage_my_process {start|stop|restart}"
fi
